server:
  servlet:
    context-path: /
    session:
      timeout: 10m
  port: 8080

spring:
  application:
    name: order-web
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 60MB
      enabled: on
  main:
    banner-mode: off
  messages:
    basename: multi-languages/info,multi-languages/error
  jackson:
    time-zone: UTC
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: off
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  task:
    scheduling:
      pool:
        size: 80
      thread-name-prefix: OrderWebScheduler-
      shutdown:
        await-termination: on
        await-termination-period: PT3M
  mvc:
    log-request-details: on
  profiles:
    active: dev
  quartz:
    properties:
      #调度标识名 集群中每一个实例都必须使用相同的名称
#      org.quartz.scheduler.instanceName: orderWebQuartzScheduler
      #ID设置为自动获取 每一个必须不同
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.makeSchedulerThreadDaemon: true
      #线程池的实现类（一般使用SimpleThreadPool即可满足需求）
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      #指定在线程池里面创建的线程是否是守护线程
      org.quartz.threadPool.makeThreadsDaemons: true
      #指定线程数，至少为1（无默认值）
      org.quartz.threadPool.threadCount: 20
      #设置线程的优先级（最大为java.lang.Thread.MAX_PRIORITY 10，最小为Thread.MIN_PRIORITY 1，默认为5）
      org.quartz.threadPool.threadPriority: 5
      #数据保存方式为数据库持久化
#      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      #数据库代理类，一般org.quartz.impl.jdbcjobstore.StdJDBCDelegate可以满足大部分数据库
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      #表的前缀，默认qrtz_
      org.quartz.jobStore.tablePrefix: qrtz_
      #是否加入集群
      org.quartz.jobStore.isClustered: false
      # 信息保存时间 默认值60秒
      org.quartz.jobStore.misfireThreshold: 25000
#      org.quartz.jobStore.dataSource: quartzDatasourcce
#      org.quartz.dataSource.quartzDatasourcce.provider: hikaricp
#      org.quartz.dataSource.quartzDatasourcce.driver: ${spring.datasource.driver-class-name}
#      org.quartz.dataSource.quartzDatasourcce.URL: ${spring.datasource.url}
#      org.quartz.dataSource.quartzDatasourcce.user: ${spring.datasource.hikari.username}
#      org.quartz.dataSource.quartzDatasourcce.password: ${spring.datasource.hikari.password}
#      org.quartz.dataSource.quartzDatasourcce.maxConnections: 5
#      org.quartz.dataSource.quartzDatasourcce.validationQuery: ${spring.datasource.hikari.connection-test-query}
    job-store-type: jdbc
    scheduler-name: orderWebQuartzScheduler
management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,restart,refresh,resume
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: on
  info:
    git:
      enabled: on
      mode: full
    java:
      enabled: on
    env:
      enabled: on
    os:
      enabled: off
    process:
      enabled: off

info:
  app:
    name: ${spring.application.name}

# 文档 https://mybatis.org/mybatis-3/index.html
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    aggressive-lazy-loading: off
    # 当查询数据为空时字段返回为null，不设置这个字段为true的话查询的数据为null时，字段将被隐藏
    call-setters-on-nulls: on
    lazy-loading-enabled: on
    local-cache-scope: session
    use-column-label: on
  type-handlers-package: com.xweb.starter.common.typehandler

security:
  invalid-session-url: /invalid-session
  expired-session-url: /session-expired
  access-denied-url: /403
  maximum-sessions:
  maxSessions-prevents-login: off
  csrf-ignore-url-patterns:
    - /
    - /error
    - /adminlte/**
    - /plugins/**
    - /img/**
    - /api/login
    - ${security.invalid-session-url}
    - ${security.expired-session-url}
    - ${security.access-denied-url}
    - /too-many-requests
  white-url-patterns:
    - ${security.api-login.login-processing-url}
    - ${security.form-login.login-processing-url}
    - /
    - /error
    - /adminlte/**
    - /plugins/**
    - /img/**
    - ${security.invalid-session-url}
    - ${security.expired-session-url}
    - /too-many-requests
  form-login:
    username-parameter: username
    password-parameter: password
    login-page: /login
    login-processing-url: /login
    default-success-url: /dashboard
    post-only: on
  api-login:
    username-parameter: username
    password-parameter: password
    login-processing-url: /api/login
    post-only: on
