server:
  servlet:
    context-path: /
    session:
      timeout: 30m
  port: 8080

spring:
  application:
    name: order-web
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 60MB
      enabled: on
  main:
    banner-mode: off
  jackson:
    time-zone: UTC
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: off
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  task:
    scheduling:
      pool:
        size: 80
      thread-name-prefix: OrderWebScheduler-
      shutdown:
        await-termination: on
        await-termination-period: PT3M
  mvc:
    log-request-details: on
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,restart,refresh,resume
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: on
  info:
    git:
      enabled: on
      mode: full
    java:
      enabled: on
    env:
      enabled: on
    os:
      enabled: off
    process:
      enabled: off

info:
  app:
    name: ${spring.application.name}

# 文档 https://mybatis.org/mybatis-3/index.html
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    aggressive-lazy-loading: off
    # 当查询数据为空时字段返回为null，不设置这个字段为true的话查询的数据为null时，字段将被隐藏
    call-setters-on-nulls: on
    lazy-loading-enabled: on
    local-cache-scope: session
    use-column-label: on
  type-handlers-package: com.xweb.starter.common.typehandler

security:
  csrf-ignore-url-patterns:
    - /
    - /error
    - /adminlte/**
    - /plugins/**
    - /img/**
    - /api/**
  white-url-patterns:
    - /login
    - /
    - /error
    - /adminlte/**
    - /plugins/**
    - /img/**
  form-login:
    username-parameter: username
    password-parameter: password
    login-page: /login
    login-processing-url: /login
    defaultSuccessUrl: /dashboard
